apiVersion: v1
kind: Service
metadata:
  name: awx-web
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: https
    port: 443
    targetPort: 8052
  selector:
    app: awx
    role: web
